name: buildx build + push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: build the image
        run: docker buildx build -f nextcloud-31.dockerfile --platform=linux/arm64 .
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: push the image
        run: |
          docker buildx build --push \
            --tag dockerteun/nextcloud-PDlib:latest \
            --platform linux/arm64 .